apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecr-creds.serviceAccountName" . }}
  labels:
    {{- include "ecr-creds.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ecr-creds.serviceAccountName" . }}
  labels:
    {{- include "ecr-creds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "ecr-creds.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
